"""posts

Revision ID: 20630a14c204
Revises: 
Create Date: 2022-10-17 12:58:29.333846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20630a14c204'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
